### ISSUE TITLE
Interfaces pour la confirmation de la facture par le client

### ISSUE THREAD

**Issue by Foris-master** [Wiicod/slim-bvs-server#18]
Créer un interface ( cote admin angular ) avec pour route ( /#/confirm-bill/'. $bill->id . '/' . $token) qui va permettre de confirmer la facture. Cette page devra : 

1. Vérifier la validete de l id de la facture et du token, ceux en appelant en GET la route api/bill/verify?bill_id=x&token=x
2. si ok, appeler la route de validation proprement dites ( api/bill/customer_comfirm) en POST en envoyant toujours bill_id et token ;
3. si ok afficher un message de succes ( en backend le status de la facture sera automatiquement change en waiting_for_cahsier_approval)

PS: l interface principale doit présenter le pdf de la facture ( embbed pdf ) et a  cote une bouton pour confirmer

**Comment by Zephyr07** [comment]
La confirmation de la facture ne fonctionne pas, le statut de la facture ne change pas.
