### ISSUE TITLE
Fichier update

### ISSUE THREAD

**Issue by Zephyr07** [Wiicod/slim-bvs-server#9]
Il faut créer un fichier update dans le projet a l’intérieur duquel tu mettras tous les updates que tu as fait avant de push.

**Comment by Foris-master** [comment]
hum , je pense que je fais deja en commentant mes commits

**Comment by Zephyr07** [comment]
Il faut un fichier consolidé genre
- version X.X.01 du 170717
    -modification de ...
    - ajoute de ....
- version X.X.02 du 180717
   - modific;
et ainsi de suite

**Comment by Foris-master** [comment]
mince s appelle le log des commits , ouvre ton phpstorm tu clique sur le onglet version control ( en bas de page de lediteur ) ensuite sur logs
